//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookbook_Database.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cookbook_Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _8_Hour_Brisket_Part_1 {
            get {
                object obj = ResourceManager.GetObject("_8_Hour_Brisket_Part_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _8_Hour_Brisket_Part_2 {
            get {
                object obj = ResourceManager.GetObject("_8_Hour_Brisket_Part_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Andys_Oatmeal_Cookies {
            get {
                object obj = ResourceManager.GetObject("Andys_Oatmeal_Cookies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Asparagus_With_Morels {
            get {
                object obj = ResourceManager.GetObject("Asparagus_With_Morels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Aunt_Dianes_Butter_Cake {
            get {
                object obj = ResourceManager.GetObject("Aunt_Dianes_Butter_Cake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bacon_Shrimp_Kebabs {
            get {
                object obj = ResourceManager.GetObject("Bacon_Shrimp_Kebabs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Beef_Bourguignon {
            get {
                object obj = ResourceManager.GetObject("Beef_Bourguignon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bills_Blueberry_Cobbler {
            get {
                object obj = ResourceManager.GetObject("Bills_Blueberry_Cobbler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Biscuits {
            get {
                object obj = ResourceManager.GetObject("Biscuits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Boston_Lettuce_Stacks_With_Grilled_Peaches_Feta_And_Pecans {
            get {
                object obj = ResourceManager.GetObject("Boston_Lettuce_Stacks_With_Grilled_Peaches_Feta_And_Pecans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Braised_Chicken_With_Shallots_Garlic_And_Balsamic_Vinegar {
            get {
                object obj = ResourceManager.GetObject("Braised_Chicken_With_Shallots_Garlic_And_Balsamic_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Braised_Lamb_Shanks_1 {
            get {
                object obj = ResourceManager.GetObject("Braised_Lamb_Shanks_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Braised_Lamb_Shanks_2 {
            get {
                object obj = ResourceManager.GetObject("Braised_Lamb_Shanks_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Braised_Veal_Shanks_With_Mashed_Potatoes_And_Tomato_Onion_Jus {
            get {
                object obj = ResourceManager.GetObject("Braised_Veal_Shanks_With_Mashed_Potatoes_And_Tomato_Onion_Jus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Broccoli_Babe_Black_Olive_And_Smoked_Mozzarella_Pizza {
            get {
                object obj = ResourceManager.GetObject("Broccoli_Babe_Black_Olive_And_Smoked_Mozzarella_Pizza", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Buttermilk_Biscuits {
            get {
                object obj = ResourceManager.GetObject("Buttermilk_Biscuits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Carmelized_Onion_And_Gruyere_Tarts {
            get {
                object obj = ResourceManager.GetObject("Carmelized_Onion_And_Gruyere_Tarts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Cedar_Planked_Salmon_With_Cider_Vinegar_Sauce {
            get {
                object obj = ResourceManager.GetObject("Cedar_Planked_Salmon_With_Cider_Vinegar_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Cheese_Scones {
            get {
                object obj = ResourceManager.GetObject("Cheese_Scones", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Chicken_And_Mushroom_Chowder {
            get {
                object obj = ResourceManager.GetObject("Chicken_And_Mushroom_Chowder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Chicken_Breast_Steamed_In_Foil {
            get {
                object obj = ResourceManager.GetObject("Chicken_Breast_Steamed_In_Foil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Chicken_Marengo {
            get {
                object obj = ResourceManager.GetObject("Chicken_Marengo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Chicken_Schnitzel_With_Capers_And_Parsley {
            get {
                object obj = ResourceManager.GetObject("Chicken_Schnitzel_With_Capers_And_Parsley", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Chili_For_4 {
            get {
                object obj = ResourceManager.GetObject("Chili_For_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Corn_Chowder {
            get {
                object obj = ResourceManager.GetObject("Corn_Chowder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Corn_Scallion_And_Potato_Frittata {
            get {
                object obj = ResourceManager.GetObject("Corn_Scallion_And_Potato_Frittata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Country_Beef_Stew_With_Whole_Garlic_Cloves {
            get {
                object obj = ResourceManager.GetObject("Country_Beef_Stew_With_Whole_Garlic_Cloves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Creamed_Spinach {
            get {
                object obj = ResourceManager.GetObject("Creamed_Spinach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Crusty_Buttermilk_Biscuits {
            get {
                object obj = ResourceManager.GetObject("Crusty_Buttermilk_Biscuits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Drews_Fish_Sauce {
            get {
                object obj = ResourceManager.GetObject("Drews_Fish_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Erwin_Salad {
            get {
                object obj = ResourceManager.GetObject("Erwin_Salad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fall_Vegetables {
            get {
                object obj = ResourceManager.GetObject("Fall_Vegetables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fettuccine_With_Sausage_And_Leeks {
            get {
                object obj = ResourceManager.GetObject("Fettuccine_With_Sausage_And_Leeks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Filet_De_Porc_Sauce_Moutarde {
            get {
                object obj = ResourceManager.GetObject("Filet_De_Porc_Sauce_Moutarde", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fish_Fillets_With_Olives_And_Oregano {
            get {
                object obj = ResourceManager.GetObject("Fish_Fillets_With_Olives_And_Oregano", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Flank_Steak_And_Orange_Slices {
            get {
                object obj = ResourceManager.GetObject("Flank_Steak_And_Orange_Slices", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Flank_Steak_With_Lemon_Mustard_Baste {
            get {
                object obj = ResourceManager.GetObject("Flank_Steak_With_Lemon_Mustard_Baste", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fried_Potatoes_With_Oregano_And_Parmesan {
            get {
                object obj = ResourceManager.GetObject("Fried_Potatoes_With_Oregano_And_Parmesan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fruit_Tart {
            get {
                object obj = ResourceManager.GetObject("Fruit_Tart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Garlic_Roasted_Broccoli_Potatoes_And_Red_Peppers {
            get {
                object obj = ResourceManager.GetObject("Garlic_Roasted_Broccoli_Potatoes_And_Red_Peppers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Goulash {
            get {
                object obj = ResourceManager.GetObject("Goulash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Goulash_Soup {
            get {
                object obj = ResourceManager.GetObject("Goulash_Soup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Green_Beans_Provencale {
            get {
                object obj = ResourceManager.GetObject("Green_Beans_Provencale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Green_Beans_With_Lemon_And_Cloves {
            get {
                object obj = ResourceManager.GetObject("Green_Beans_With_Lemon_And_Cloves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Grilled_Chicken_For_Mustard_Lovers {
            get {
                object obj = ResourceManager.GetObject("Grilled_Chicken_For_Mustard_Lovers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Grilled_Jerk_Pork_Chops {
            get {
                object obj = ResourceManager.GetObject("Grilled_Jerk_Pork_Chops", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Grilled_Lemon_Chicken {
            get {
                object obj = ResourceManager.GetObject("Grilled_Lemon_Chicken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Grilled_Marinated_Pork_With_Jamaican_Spread_Part_1 {
            get {
                object obj = ResourceManager.GetObject("Grilled_Marinated_Pork_With_Jamaican_Spread_Part_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Grilled_Marinated_Pork_With_Jamaican_Spread_Part_2 {
            get {
                object obj = ResourceManager.GetObject("Grilled_Marinated_Pork_With_Jamaican_Spread_Part_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Herb_And_Bacon_Corn_Bread_Stuffing {
            get {
                object obj = ResourceManager.GetObject("Herb_And_Bacon_Corn_Bread_Stuffing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Herb_Coated_Crab_Cakes {
            get {
                object obj = ResourceManager.GetObject("Herb_Coated_Crab_Cakes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Herb_Crusted_Red_Trout_Fillets_With_Lemon_Beurre_Blanc {
            get {
                object obj = ResourceManager.GetObject("Herb_Crusted_Red_Trout_Fillets_With_Lemon_Beurre_Blanc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hitt_Salad {
            get {
                object obj = ResourceManager.GetObject("Hitt_Salad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hitt_Salad_Dressing {
            get {
                object obj = ResourceManager.GetObject("Hitt_Salad_Dressing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Home_Fries_With_Onions_And_Chives {
            get {
                object obj = ResourceManager.GetObject("Home_Fries_With_Onions_And_Chives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hot_Chocolate_Souffle {
            get {
                object obj = ResourceManager.GetObject("Hot_Chocolate_Souffle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jerk_Seasoning {
            get {
                object obj = ResourceManager.GetObject("Jerk_Seasoning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kale_Winter_Hash {
            get {
                object obj = ResourceManager.GetObject("Kale_Winter_Hash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lamb_Chops_With_Garlic_And_Marjoram {
            get {
                object obj = ResourceManager.GetObject("Lamb_Chops_With_Garlic_And_Marjoram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lamb_Kebabs {
            get {
                object obj = ResourceManager.GetObject("Lamb_Kebabs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Leek_And_Goat_Cheese_Tart {
            get {
                object obj = ResourceManager.GetObject("Leek_And_Goat_Cheese_Tart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Leg_Of_Lamb_Anchoiade_With_Gigondas {
            get {
                object obj = ResourceManager.GetObject("Leg_Of_Lamb_Anchoiade_With_Gigondas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lemony_Herbed_Chicken {
            get {
                object obj = ResourceManager.GetObject("Lemony_Herbed_Chicken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lentils_With_Bacon {
            get {
                object obj = ResourceManager.GetObject("Lentils_With_Bacon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lime_Marinated_Skirt_Steak_Kebabs {
            get {
                object obj = ResourceManager.GetObject("Lime_Marinated_Skirt_Steak_Kebabs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Maple_Glazed_Roast_Turkey {
            get {
                object obj = ResourceManager.GetObject("Maple_Glazed_Roast_Turkey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Marinated_Ribeye_Steak_With_Corn_Relish {
            get {
                object obj = ResourceManager.GetObject("Marinated_Ribeye_Steak_With_Corn_Relish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mixed_Vegetable_Grill {
            get {
                object obj = ResourceManager.GetObject("Mixed_Vegetable_Grill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Moms_Crumb_Cake {
            get {
                object obj = ResourceManager.GetObject("Moms_Crumb_Cake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mushroom_And_Shallot_Red_Wine_Sauce {
            get {
                object obj = ResourceManager.GetObject("Mushroom_And_Shallot_Red_Wine_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mustard_Glazed_Baby_Carrots {
            get {
                object obj = ResourceManager.GetObject("Mustard_Glazed_Baby_Carrots", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mustard_Roasted_Fish {
            get {
                object obj = ResourceManager.GetObject("Mustard_Roasted_Fish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Nancys_Broccoli_Slaw {
            get {
                object obj = ResourceManager.GetObject("Nancys_Broccoli_Slaw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] New_England_Clam_Chowder {
            get {
                object obj = ResourceManager.GetObject("New_England_Clam_Chowder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Onion_Tart {
            get {
                object obj = ResourceManager.GetObject("Onion_Tart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Orange_Soy_Baby_Back_Ribs {
            get {
                object obj = ResourceManager.GetObject("Orange_Soy_Baby_Back_Ribs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Osso_Bucco_With_Tomatoes_Olives_And_Gremolata {
            get {
                object obj = ResourceManager.GetObject("Osso_Bucco_With_Tomatoes_Olives_And_Gremolata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Osso_Buco_Alla_Milanese {
            get {
                object obj = ResourceManager.GetObject("Osso_Buco_Alla_Milanese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Oven_Baked_Baby_Potatoes {
            get {
                object obj = ResourceManager.GetObject("Oven_Baked_Baby_Potatoes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pasta_With_Broccoli_Rabe_Goat_Cheese_Sun_Dried_Tomatoes_And_Pine_Nuts {
            get {
                object obj = ResourceManager.GetObject("Pasta_With_Broccoli_Rabe_Goat_Cheese_Sun_Dried_Tomatoes_And_Pine_Nuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pear_Pine_Nut_And_Cheese_Salad {
            get {
                object obj = ResourceManager.GetObject("Pear_Pine_Nut_And_Cheese_Salad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Perfect_Black_Olives_Tapenade {
            get {
                object obj = ResourceManager.GetObject("Perfect_Black_Olives_Tapenade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pomes_De_Terre_Aux_Champignons {
            get {
                object obj = ResourceManager.GetObject("Pomes_De_Terre_Aux_Champignons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Potato_Gratin {
            get {
                object obj = ResourceManager.GetObject("Potato_Gratin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Quick_Cassoulet {
            get {
                object obj = ResourceManager.GetObject("Quick_Cassoulet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Red_Kuri_Squash_Puree {
            get {
                object obj = ResourceManager.GetObject("Red_Kuri_Squash_Puree", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roast_Duck_Breast_With_Balsamic_And_Apricot_Sauce {
            get {
                object obj = ResourceManager.GetObject("Roast_Duck_Breast_With_Balsamic_And_Apricot_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roast_Pork_With_Balsamic_Vinegar_And_Sage {
            get {
                object obj = ResourceManager.GetObject("Roast_Pork_With_Balsamic_Vinegar_And_Sage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roasted_Black_Sea_Bass_With_Israeli_Couscous_And_Wild_Mushrooms {
            get {
                object obj = ResourceManager.GetObject("Roasted_Black_Sea_Bass_With_Israeli_Couscous_And_Wild_Mushrooms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roasted_Butternut_Squash_Pancetta_Balsamic_Parmesan_And_Kerb_Headcrumbs {
            get {
                object obj = ResourceManager.GetObject("Roasted_Butternut_Squash_Pancetta_Balsamic_Parmesan_And_Kerb_Headcrumbs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roasted_Salmon_With_Mushroom_And_Shallot_Red_Wine_Sauce {
            get {
                object obj = ResourceManager.GetObject("Roasted_Salmon_With_Mushroom_And_Shallot_Red_Wine_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roasted_Squash_And_Brussels_Sprouts {
            get {
                object obj = ResourceManager.GetObject("Roasted_Squash_And_Brussels_Sprouts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rosemary_Pork_Loin_Chops {
            get {
                object obj = ResourceManager.GetObject("Rosemary_Pork_Loin_Chops", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Salad_Of_Black_Beans_Hearts_Of_Palm_And_Corn {
            get {
                object obj = ResourceManager.GetObject("Salad_Of_Black_Beans_Hearts_Of_Palm_And_Corn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Salmon_With_Sugar_Snap_Peas_And_Bacon {
            get {
                object obj = ResourceManager.GetObject("Salmon_With_Sugar_Snap_Peas_And_Bacon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sauteed_Duck_Breasts_With_Pan_Asian_Flavors {
            get {
                object obj = ResourceManager.GetObject("Sauteed_Duck_Breasts_With_Pan_Asian_Flavors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Scallops_With_Asparagus {
            get {
                object obj = ResourceManager.GetObject("Scallops_With_Asparagus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Scrambled_Eggs___Potatoes {
            get {
                object obj = ResourceManager.GetObject("Scrambled_Eggs___Potatoes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shitake_Beef_Stroganov {
            get {
                object obj = ResourceManager.GetObject("Shitake_Beef_Stroganov", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shredded_Potato_Cake {
            get {
                object obj = ResourceManager.GetObject("Shredded_Potato_Cake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skirt_Steak_Marinade_With_Chimichurri {
            get {
                object obj = ResourceManager.GetObject("Skirt_Steak_Marinade_With_Chimichurri", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Snickerdoodles {
            get {
                object obj = ResourceManager.GetObject("Snickerdoodles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Southwestern_Black_Bean_Soup_With_Tequila_Lime_Sour_Cream {
            get {
                object obj = ResourceManager.GetObject("Southwestern_Black_Bean_Soup_With_Tequila_Lime_Sour_Cream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spice_Bread_With_Pears {
            get {
                object obj = ResourceManager.GetObject("Spice_Bread_With_Pears", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sugar_Cookies {
            get {
                object obj = ResourceManager.GetObject("Sugar_Cookies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Taku_Lodge_Basted_Grilled_Salmon {
            get {
                object obj = ResourceManager.GetObject("Taku_Lodge_Basted_Grilled_Salmon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tenderloin_Filets_With_Mushroom_Shallot_And_Merlot_Sauce {
            get {
                object obj = ResourceManager.GetObject("Tenderloin_Filets_With_Mushroom_Shallot_And_Merlot_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] The_Best_Crispy_Roast_Potatoes_Ever_Recipe_Part_1 {
            get {
                object obj = ResourceManager.GetObject("The_Best_Crispy_Roast_Potatoes_Ever_Recipe_Part_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] The_Best_Crispy_Roast_Potatoes_Ever_Recipe_Part_2 {
            get {
                object obj = ResourceManager.GetObject("The_Best_Crispy_Roast_Potatoes_Ever_Recipe_Part_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Thick_Cut_Out_Sugar_Cookies {
            get {
                object obj = ResourceManager.GetObject("Thick_Cut_Out_Sugar_Cookies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tomato_Basil_Soup {
            get {
                object obj = ResourceManager.GetObject("Tomato_Basil_Soup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tomato_Mozzarella_And_Basil_Salad_Glucksman {
            get {
                object obj = ResourceManager.GetObject("Tomato_Mozzarella_And_Basil_Salad_Glucksman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Turnip_Potato_Puree {
            get {
                object obj = ResourceManager.GetObject("Turnip_Potato_Puree", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tuscan_White_Bean___Pasta_Soup {
            get {
                object obj = ResourceManager.GetObject("Tuscan_White_Bean___Pasta_Soup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Underskin_Stuffed_Chicken_San_Francisco_Part_1 {
            get {
                object obj = ResourceManager.GetObject("Underskin_Stuffed_Chicken_San_Francisco_Part_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Underskin_Stuffed_Chicken_San_Francisco_Part_2 {
            get {
                object obj = ResourceManager.GetObject("Underskin_Stuffed_Chicken_San_Francisco_Part_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Veal_Cutlets_With_Arugula_And_Tomato_Salad {
            get {
                object obj = ResourceManager.GetObject("Veal_Cutlets_With_Arugula_And_Tomato_Salad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Vegetables_Printanier {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Printanier", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Vie_Cream_Of_Broccoli_Soup {
            get {
                object obj = ResourceManager.GetObject("Vie_Cream_Of_Broccoli_Soup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Vie_Flatbread {
            get {
                object obj = ResourceManager.GetObject("Vie_Flatbread", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Vie_Roasted_Quail {
            get {
                object obj = ResourceManager.GetObject("Vie_Roasted_Quail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Vie_Sausage {
            get {
                object obj = ResourceManager.GetObject("Vie_Sausage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Warm_Frisee_Salad_With_Poached_Eggs_In_Red_Wine_Sauce {
            get {
                object obj = ResourceManager.GetObject("Warm_Frisee_Salad_With_Poached_Eggs_In_Red_Wine_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wild_Mushroom_And_Asparagus_Salad {
            get {
                object obj = ResourceManager.GetObject("Wild_Mushroom_And_Asparagus_Salad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wild_Mushroom_Soup {
            get {
                object obj = ResourceManager.GetObject("Wild_Mushroom_Soup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Winter_White_Bean_Soup {
            get {
                object obj = ResourceManager.GetObject("Winter_White_Bean_Soup", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
